CREATE TABLE IF NOT EXISTS ledger (
	id BIGSERIAL PRIMARY KEY,
	reward_id BIGINT REFERENCES rewards(id) ON DELETE CASCADE,
	symbol VARCHAR(10) REFERENCES stocks(symbol),
	quantity NUMERIC(18,6) NOT NULL,
	inr_cost NUMERIC(18,4) NOT NULL,
	brokerage_fee NUMERIC(18,4) NOT NULL DEFAULT 0,
	stt_tax NUMERIC(18,4) NOT NULL DEFAULT 0,
	gst_fee NUMERIC(18,4) NOT NULL DEFAULT 0,
	other_fees NUMERIC(18,4) NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT NOW()
);
